[workspace]
members = ["examples/*"]

[package]
name = "bevy-kira-components"
description = "Alternative crate for Bevy integration of Kira"
license = "MIT"
homepage = "https://github.com/solarliner/bevy-kira-components"
repository = "https://github.com/solarliner/bevy-kira-components.git"
version = "0.2.0-rc.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_math = { version = "0.16", features = ["mint"] }
cpal = "0.15.3"
kira = { version = "0.9", features = ["serde"] }
thiserror = "2"
serde = { version = "1", features = ["derive"] }

[dependencies.bevy]
version = "0.16"
default-features = false
features = ["bevy_asset", "bevy_color", "bevy_gizmos", "bevy_log", "std"]

[dev-dependencies]
ringbuf = "0.4"

[dev-dependencies.bevy]
version = "0.16"
default-features = false
features = [
    # Copied from bevy with "bevy_audio" removed
    "std",
    "async_executor",
    "android-game-activity",
    "android_shared_stdcxx",
    "animation",
    "bevy_asset",
    "bevy_color",
    "bevy_core_pipeline",
    "bevy_gilrs",
    "bevy_gizmos",
    "bevy_gltf",
    "bevy_input_focus",
    "bevy_log",
    "bevy_mesh_picking_backend",
    "bevy_pbr",
    "bevy_picking",
    "bevy_render",
    "bevy_scene",
    "bevy_sprite",
    "bevy_sprite_picking_backend",
    "bevy_state",
    "bevy_text",
    "bevy_ui",
    "bevy_ui_picking_backend",
    "bevy_window",
    "bevy_winit",
    "custom_cursor",
    "default_font",
    "hdr",
    "multi_threaded",
    "png",
    "smaa_luts",
    "sysinfo_plugin",
    "tonemapping_luts",
    "vorbis",
    "webgl2",
    "x11",
]

[features]
default = []
diagnostics = []
